AWSTemplateFormatVersion: '2010-09-09'
Description: My Sample SecurityGroup Template

# -----------------------------------
Resources:
# -----------------------------------
  FirstSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:  PublicSubnet
      GroupDescription: PublicSubnet
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicSubnet
      VpcId: !ImportValue FirstVPCId