AWSTemplateFormatVersion: '2010-09-09'
Description: My Sample VPC Template

# -----------------------------------
Resources:
# -----------------------------------
  FirstVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags: 
      - Key: Name
        Value: firstVPC

  FirstInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
      - Key: Name
        Value: firstVPC-IGW
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FirstVPC
      InternetGatewayId: !Ref FirstInternetGateway

  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref FirstVPC
      Tags: 
      - Key: Name
        Value: firstVPC-FrontendRoute

  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FirstInternetGateway

  FrontendSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref FirstVPC
      Tags: 
      - Key: Name
        Value: FirstVPC-FrontendSubnet

  FrontendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet
      RouteTableId: !Ref FrontendRouteTable

# -----------------------------------
Outputs:
# -----------------------------------
  FirstVPCId:
    Description: FirstVPCId
    Value: !Ref FirstVPC
    Export: 
      Name: FirstVPCId

  FrontendSubnetId:
    Description: FrontendSubnetId
    Value: !Ref FrontendSubnet
    Export: 
      Name: FrontendSubnetId